export { default as About } from "./About";
export { default as ChangeStatus } from "./ChangeStatus";;
export { default as ClubFound } from "./ClubFound";
export { default as Distinctions } from "./Distinctions";
export { default as Gallery } from "./Gallery";
export { default as GalleryModal } from "./GalleryModal";
export { default as Palmares } from "./Palmares";
export { default as PlayerClubItem } from "./PlayerClubItem"
export { default as PlayerNationalItem } from "./PlayerNationalItem";
export { default as ProfileCard } from "./ProfileCard";
export { default as RandomProfile } from "./RandomProfile"
export { default as Report } from "./Report";
export { default as StatisticItem } from "./StatisticItem";
export { default as Trajectory } from "./Trajectory";
export { default as Trophies } from "./Trophies";
export { default as VideoGallery } from "./VideoGallery";
export { default as VideoList } from "./VideoList";
